import streamlit as st

def app():
    st.markdown("<h2 style='text-align: center; color: #3b82f6;'>Customer Retention Insights</h2>", unsafe_allow_html=True)
    
    with st.container():
        st.markdown("""
        <div style="background-color: #f0f2f6; padding: 25px; border-radius: 15px; box-shadow: 0 0 10px rgba(0,0,0,0.05); font-size: 16px;">
            <h4 style="color: #3b82f6;">Model Comparison Summary</h4>
            <p>This section highlights key features identified by XGBoost and SVM models in predicting customer churn, along with practical business recommendations to improve customer retention.</p>
        </div>
        """, unsafe_allow_html=True)

        st.markdown("#### Feature Insights by Model")
        st.markdown("""
        | **Kategori**                | **XGBoost**                                                       | **SVM**                                                            | **Kesimpulan**                                                      |
        |-----------------------------|-------------------------------------------------------------------|--------------------------------------------------------------------|---------------------------------------------------------------------|
        | **Fitur Retensi Churn**     | Total_Trans_Ct, Total_Trans_Amt, Total_Relationship_Count, Total_Revolving_Bal                                                                                  | Total_Trans_Ct, Total_Trans_Amt, Total_Revolving_Bal, Total_Ct_Chng_Q4_Q1                                                                                               | Frekuensi dan nilai transaksi utama menunjukkan loyalitas. Pada SVM, perubahan jumlah transaksi (Total_Ct_Chng_Q4_Q1) juga menjadi indikator retensi.                         |
        | **Fitur Pemicu Churn**      | Total_Amt_Chng_Q4_Q1, Months_Inactive_12_mon, Contacts_Count_12_mon, Credit_Limit                                                                               | Months_Inactive_12_mon, Contacts_Count_12_mon, Customer_Age, Avg_Utilization_Ratio                                                                                     | Perubahan pola transaksi dan berkurangnya interaksi (ditandai oleh peningkatan bulan tidak aktif dan kontak yang lebih sedikit) mengindikasikan potensi churn.              |
        | **Fitur Tidak Berpengaruh** | Education_Level_Unknown, Education_Level_Graduate, Income_Category_Unknown                                                                                      | Income_Category_Unknown, Education_Level_Post-Graduate                                                                                                               | Variabel kategori pendidikan dan pendapatan cenderung memiliki pengaruh minimal terhadap churn dalam kedua model.                                                           |
        | **Fitur Negatif**           | Marital_Status_Single, Education_Level_High School, Income_Category_Less than 40K<br>(fitur dengan nilai negatif lebih besar dalam XGBoost)                  | Education_Level_Graduate, Income_Category_Less than 40K, Income_Category_60K - 80K<br>(nilai negatif yang dominan menunjukkan kecenderungan risiko churn)          | Nilai negatif menunjukkan bahwa kenaikan fitur-fitur tersebut (yang berkaitan dengan demografi atau aspek interaksi tertentu) dapat dikaitkan dengan meningkatnya risiko churn. |
        | **Perbedaan Model**         | Menitikberatkan volume dan nilai transaksi total sebagai indikator loyalitas.                                                                                  | Lebih menekankan dinamika perubahan (misalnya, perubahan jumlah transaksi) serta durasi tidak aktif.                                                                    | XGBoost lebih fokus pada aspek kuantitatif transaksi, sedangkan SVM menangkap dinamika perilaku yang berubah seiring waktu.                                                   |
        | **Hubungan Fitur dengan Churn** | Pelanggan dengan transaksi yang konsisten dan hubungan relasional yang baik cenderung menunjukkan loyalitas yang lebih tinggi.                                | Pola transaksi yang berfluktuasi, terutama jika diiringi periode tidak aktif atau penurunan jumlah kontak, cenderung meningkatkan risiko churn.                           | Keterlibatan pelanggan secara aktif adalah kunci retensi; perubahan signifikan dalam perilaku transaksi dapat memicu kemungkinan churn.                                      |
        """, unsafe_allow_html=True)

        st.markdown("#### 💡 Business Recommendations")
        st.markdown("""
        | **Rekomendasi Bisnis**                                  | **Tindakan**                                                                                                                                                                                                                                                                                                               |
        |---------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
        | **Dorong Peningkatan Frekuensi dan Nilai Transaksi**    | - Tingkatkan **Total_Trans_Ct** dan **Total_Trans_Amt** melalui program loyalitas, cashback, atau diskon khusus.<br> - Dorong pelanggan untuk bertransaksi lebih sering dengan penawaran eksklusif dan promosi terjadwal.                                                                                                   |
        | **Perluas Hubungan dengan Pelanggan**                   | - Tingkatkan **Total_Relationship_Count** dengan menawarkan lebih banyak produk atau layanan per pelanggan.<br> - Terapkan pendekatan **cross-selling** dan **upselling** yang dipersonalisasi untuk memperkuat loyalitas.                                                                                                   |
        | **Manajemen Saldo yang Seimbang**                       | - Pantau **Total_Revolving_Bal** untuk menghindari saldo bergulir yang tinggi.<br> - Sesuaikan **Credit_Limit** secara strategis agar tetap kompetitif dan sesuai kemampuan pelanggan.<br> - Berikan edukasi pengelolaan keuangan untuk meningkatkan retensi.                                                               |
        | **Aktifkan Kembali Pelanggan yang Pasif**               | - Fokus pada **Months_Inactive_12_mon** dan **Contacts_Count_12_mon** untuk mengidentifikasi pelanggan pasif.<br> - Lakukan pendekatan re-engagement seperti reminder transaksi, penawaran khusus, atau konsultasi personal.                                                                                                |
        | **Pantau Perubahan Pola Perilaku Pelanggan**            | - Monitor **Total_Ct_Chng_Q4_Q1** dan **Total_Amt_Chng_Q4_Q1** untuk mendeteksi perubahan pola transaksi yang signifikan.<br> - Terapkan sistem peringatan dini dan intervensi otomatis untuk pelanggan dengan pola transaksi yang tidak stabil.                                                                           |
        | **Perhatikan Risiko Berdasarkan Profil Pengguna**       | - Waspadai segmen usia tertentu berdasarkan fitur **Customer_Age**.<br> - Evaluasi **Avg_Utilization_Ratio** untuk mengidentifikasi potensi risiko finansial yang dapat menyebabkan churn.                                                                                                                               |
        | **Optimalkan Strategi Berdasarkan Aktivitas Pelanggan** | - Karena **Income_Category_Unknown**, **Income_Category_80K - 120K**, **Education_Level_Unknown**, **Education_Level_Post-Graduate**, **Education_Level_Uneducated**, dan **Education_Level_College** tidak berpengaruh signifikan atau berdampak negatif, fokuskan strategi pada pola perilaku pelanggan.<br> - Prioritaskan interaksi dan keterlibatan pelanggan ketimbang data demografis. |
        """, unsafe_allow_html=True)
